# Generated by Django 5.0 on 2023-12-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_create_message_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Subject'),
        ),
    ]
